# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Backend Test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    FRONTEND_URL: ""
    DATABASE_URL: ""
    JWT_SECRET_KEY: "secret"
    JWT_ALGORITHM: "HS256"
    JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "300"
    JWT_REFRESH_TOKEN_EXPIRE_MINUTES: "10080"
    CLOUDINARY_API_KEY: ""
    CLOUDINARY_CLOUD_NAME: ""
    CLOUDINARY_API_SECRET: ""

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend/app

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Lint with flake8
              run: |
                  # stop the build if there are Python syntax errors or undefined names
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: Install pytest dependencies
              run: pip install pytest pytest-md pytest-emoji
            - name: Run pytest
              uses: pavelzw/pytest-action@v2
              with:
                verbose: true
                emoji: true
                job-summary: true
                custom-arguments: '-q'
                click-to-expand: true
                report-title: 'Test Report'
